# Generated by Django 5.2.12 on 2026-04-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='governorate',
            field=models.CharField(blank=True, choices=[('Ajloun', 'Ajloun'), ('Amman', 'Amman'), ('Aqaba', 'Aqaba'), ('Balqa', 'Balqa'), ('Irbid', 'Irbid'), ('Jerash', 'Jerash'), ('Karak', 'Karak'), ('Maan', 'Maan'), ('Madaba', 'Madaba'), ('Mafraq', 'Mafraq'), ('Tafilah', 'Tafilah'), ('Zarqa', 'Zarqa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='weather',
            field=models.CharField(blank=True, choices=[('Sunny', 'Clear/Sunny'), ('Partially Cloudy', 'Partially Cloudy'), ('Cloudy', 'Cloudy/Overcast'), ('Foggy', 'Fog/Mist'), ('Rainy', 'Rain'), ('Snowy', 'Snow'), ('Stormy', 'Thunderstorm'), ('Hazy', 'Haze/Smoke/Dust')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='description_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='is_endangered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='is_endemic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='is_invasive',
            field=models.BooleanField(default=False),
        ),
    ]
