# Generated by Django 5.2.12 on 2026-04-12 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observation_governorate_observation_weather_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='observations.observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='observations.observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('observation', 'user')},
            },
        ),
    ]
