# Generated by Django 5.2.13 on 2026-04-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='genus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='order',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
