# Generated by Django 5.2.13 on 2026-05-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_quest_category_quest_geographic_area_quest_image_and_more'),
        ('observations', '0005_observationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='gamification.quest'),
        ),
    ]
