# Generated by Django 5.2.13 on 2026-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_observation_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
