# Generated by Django 5.2.13 on 2026-04-23 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CLASS', 'Class'), ('ORDER', 'Order'), ('FAMILY', 'Family'), ('GENUS', 'Genus'), ('SPECIES', 'Species')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('researcher', models.ForeignKey(limit_choices_to={'role': 'RESEARCHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('researcher', 'level', 'name')},
            },
        ),
    ]
