# Generated by Django 5.2.13 on 2026-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_pts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
