# Generated by Django 5.2.13 on 2026-05-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_total_pts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_pts',
        ),
    ]
