services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:                  
    image: redis:alpine
    restart: always

  web:
    build: .
    restart: always
    entrypoint: ["/app/entrypoint.sh"]
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - model_data:/app/observations/6
      - model_data_v2:/app/observations/epoch_1
      - hf_cache:/root/.cache/huggingface
    depends_on:
      - db
      - redis    
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  postgres_data:
  model_data:
  model_data_v2:
  hf_cache:
  caddy_data:
  caddy_config:
  