# Generated by Django 5.2.13 on 2026-05-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        ('observations', '0005_observationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.CharField(choices=[('PLANT', 'Plant'), ('INSECT', 'Insect'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='quest',
            name='geographic_area',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quests/'),
        ),
        migrations.AddField(
            model_name='quest',
            name='reward_pts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quest',
            name='target_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quest',
            name='target_species',
            field=models.ManyToManyField(blank=True, related_name='quests', to='observations.species'),
        ),
        migrations.AddField(
            model_name='userquest',
            name='observation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed/Expired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
