# Generated by Django 5.2.13 on 2026-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_quest_category_quest_geographic_area_quest_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='criteria',
        ),
        migrations.AddField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(blank=True, choices=[('OBSERVATION_COUNT', 'Observation Count'), ('QUEST_COUNT', 'Quests Completed'), ('FIRST_SPECIES', 'First Species Discovery')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='criteria_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
